INSERT INTO PHONE_TYPE(NAME)
VALUES('PHONE_HOME');
INSERT INTO PHONE_TYPE(NAME)
VALUES('PHONE_WORK');
INSERT INTO PHONE_TYPE(NAME)
VALUES('PHONE_CELL_HOME');
INSERT INTO PHONE_TYPE(NAME)
VALUES('PHONE_CELL_WORK');
COMMIT;

